// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWG4CTpKEXoISAQ2ZbWTqQJsWAb1gF-s',
    appId: '1:169486636262:web:4d5374ed352b549c53d727',
    messagingSenderId: '169486636262',
    projectId: 'first-3dba4',
    authDomain: 'first-3dba4.firebaseapp.com',
    storageBucket: 'first-3dba4.firebasestorage.app',
    measurementId: 'G-FW91EYXW6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoBVJ48w_51a3xT7gFXMyn1HlutcXik3M',
    appId: '1:169486636262:android:dfb180498bc73ef953d727',
    messagingSenderId: '169486636262',
    projectId: 'first-3dba4',
    storageBucket: 'first-3dba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuaa21Dz3s0SODxtTJO-f27EtZtJMzkE',
    appId: '1:169486636262:ios:c4604ff069e1cd4953d727',
    messagingSenderId: '169486636262',
    projectId: 'first-3dba4',
    storageBucket: 'first-3dba4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
